name: AutoVIP
main: fr.yahoo.diabolomenthe75005.AutoVIP.AutoVIP
version: 1.2
database: true

commands:
  autovip:
    description: AutoVIP.
    usage: /autovip <player> <forumname>
    aliases:
    - av